### ISSUE TITLE
ESP8266 subscribe example

### ISSUE THREAD

**Issue by hixfield** [ibm-watson-iot/device-arduino#14]
the ESP8266 example does not include a demo with pubsubclient.subscribe(...) functionality to send a command back to the device. I have trouble getting this to work together with the nodered BlueMix app.

Would it be possible to update the example to include subscribe functionality e.g. switching on/off a LED on one of the GPIO pins together with nodered config in BlueMix?

**Comment by MaeveOReilly** [comment]
There is as sketch in [this recipe](https://developer.ibm.com/recipes/tutorials/build-your-own-watson-controlled-kettle/) with a subscribe for commands.

**Comment by amitmangalvedkar** [comment]
@hixfield Does @MaeveOReilly 's recipe help?

**Comment by amitmangalvedkar** [comment]
Closing this issue, in case @hixfield gets the issue again, it can be reopened
