### ISSUE TITLE
Some Ethernet shields use Ethernet2

### ISSUE THREAD

**Issue by EOC** [ibm-watson-iot/device-arduino#9]
Hi,

In the samples the Ethernet library used is <Ethernet.h>, on some of the newer shields from Arduino.org the shield uses Ethernet2, http://www.arduino.org/products/shields/arduino-ethernet-shield-2. 

Some beginners might not know this, maybe just add a commented out header or comment to the code that #include <Ethernet2.h> will be needed depending on your Ethernet shield type.

Thanks,

Eoin

**Comment by sathipal** [comment]
Committed the changes.
